_wandb:
    value:
        cli_version: 0.21.3
        e:
            3syveuz2ofk39p2byzra02jpqyz3tsnv:
                codePath: prototypes+/btquant_v2025_cutting_edge.py
                codePathLocal: prototypes+/btquant_v2025_cutting_edge.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "462839042048"
                        used: "377607770112"
                email: aLcaTr4z@gmail.com
                executable: /home/alca/projects/.btq/bin/python
                git:
                    commit: 7ff351c5ff8460e41393c0b3a28b7e15ba792418
                    remote: https://github.com/itsXactlY/BTQuant/
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-e48e4469-9bdd-ab8f-8c16-ec2a1c0101ab
                host: alca
                memory:
                    total: "33592832000"
                os: Linux-6.16.4-zen1-1-zen-x86_64-with-glibc2.42
                program: /home/alca/projects/BTQuant/prototypes+/btquant_v2025_cutting_edge.py
                python: CPython 3.13.7
                root: /home/alca/projects/BTQuant
                startedAt: "2025-09-05T19:42:44.650998Z"
                writerId: 3syveuz2ofk39p2byzra02jpqyz3tsnv
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 77
            "2":
                - 1
                - 5
                - 35
                - 53
                - 77
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 32
bear_end:
    value: "2023-06-23"
bear_start:
    value: "2022-05-28"
bull_end:
    value: "2021-05-31"
bull_start:
    value: "2020-09-28"
cache_dir:
    value: .btq_cache_v2025
commission:
    value: 0.00075
gamma:
    value: 0.99
gnn_hidden_dim:
    value: 64
init_cash:
    value: 10000
learning_rate:
    value: 0.0003
max_drawdown_threshold:
    value: 0.15
max_position_size:
    value: 0.2
num_attention_heads:
    value: 4
num_transformer_layers:
    value: 3
regime_lookback:
    value: 252
rl_algorithm:
    value: PPO
slippage_bps:
    value: 5
symbols:
    value:
        - BTC
        - ETH
test_end:
    value: "2025-05-31"
test_start:
    value: "2023-06-12"
timeframe:
    value: 15m
transformer_dim:
    value: 128
use_gpu:
    value: true
use_macro_data:
    value: true
use_options_flow:
    value: true
use_regime_detection:
    value: true
use_sentiment:
    value: true
var_confidence:
    value: 0.05
