_wandb:
    value:
        cli_version: 0.21.3
        e:
            n9azasj4bie8mq0dz5crzr4ez59f4ux6:
                codePath: neural_trading_system/neural_pipeline.py
                codePathLocal: neural_pipeline.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "462839042048"
                        used: "348147216384"
                email: aLcaTr4z@gmail.com
                executable: /home/alca/projects/.btq/bin/python
                git:
                    commit: d8dd2f13c6a04ff9554f3ff80b81b670ccd7cf07
                    remote: https://github.com/itsXactlY/BTQuant/
                gpu: NVIDIA GeForce GTX 1070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1920
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1070
                      uuid: GPU-e48e4469-9bdd-ab8f-8c16-ec2a1c0101ab
                host: alca
                memory:
                    total: "33592393728"
                os: Linux-6.17.2-zen1-1-zen-x86_64-with-glibc2.42
                program: /home/alca/projects/BTQuant/neural_trading_system/neural_pipeline.py
                python: CPython 3.13.7
                root: /home/alca/projects/BTQuant/neural_trading_system
                startedAt: "2025-10-21T21:59:18.992361Z"
                writerId: n9azasj4bie8mq0dz5crzr4ez59f4ux6
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
            "2":
                - 1
                - 5
                - 35
                - 53
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 4
d_model:
    value: 256
device:
    value: cuda
feature_dim:
    value: 2164
lookback_windows:
    value:
        - 5
        - 10
num_epochs:
    value: 10
num_heads:
    value: 8
num_layers:
    value: 1
prediction_horizon:
    value: 1
seq_len:
    value: 10
